#!/bin/bash

hcc ` hcc-config --cxxflags ` -DSTATIC_LIB static_library1.cpp -c -o static_library1.o
ar rcs libstatic_library1.a static_library1.o
hcc `hcc-config --cxxflags --ldflags` -L ./ -lstatic_library1 static_library1.cpp -o test

