#!/bin/bash

hcc `hcc-config --cxxflags --ldflags` hcc_bandwidth.cpp -lStackTimer -L utilities/  -I utilities/include/ -lhc_am -I/opt/rocm/profiler/CXLActivityLogger/include/ -L/opt/rocm/profiler/CXLActivityLogger/bin/x86_64/ -lCXLActivityLogger -o hcc_bandwidth
