#!/bin/bash
set -x

hcc -hc  hcc_bandwidth.cpp -lStackTimer -L utilities/  -I utilities/include/ -lhc_am  -o hcc_bandwidth

hcc -hc copy_test.cpp -lStackTimer -L utilities/  -I utilities/include/ -o copy_test
